#!/usr/bin/env node
// Generate forge-abilities/CATALOG.md — a scannable table of every authored
// ability so an author can spot a matching base ability BEFORE writing a new one.
// Pure `buildCatalog` (markdown from rows) + a `main()` that does the fs read/write.
// Run on its own via `npm run content:catalog`, and at the start of packs:build so
// it never goes stale. Committed (visible in PR diffs).
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { MODULES, COLLECTIONS } from "./modules.mjs";

const DESC_LEN = 120;

// Markdown table-cell safe: strip tags, collapse whitespace, escape pipes, clip.
function cell(s, clip) {
  let t = String(s ?? "").replace(/<[^>]*>/g, "").replace(/\s+/g, " ").trim();
  if (clip && t.length > clip) t = t.slice(0, clip - 1).trimEnd() + "…";
  return t.replace(/\|/g, "\\|");
}

export function buildCatalog(rows) {
  const sorted = [...rows].sort((a, b) => a.identifier.localeCompare(b.identifier));
  const head = "| Identifier | Name | Tier | Icon | Description |";
  const sep = "| --- | --- | --- | --- | --- |";
  const body = sorted.map(r =>
    `| \`${cell(r.identifier)}\` | ${cell(r.name)} | ${cell(r.tier) || "—"} | ${cell(r.img)} | ${cell(r.description, DESC_LEN)} |`,
  );
  return [
    "<!-- GENERATED by scripts/pack-tools/catalog.mjs — do not edit by hand. Run `npm run content:catalog`. -->",
    "# Ability Catalog",
    "",
    `${sorted.length} authored abilities. Reuse a matching base before authoring new.`,
    "",
    head, sep, ...body, "",
  ].join("\n");
}

// Read every item-collection pack's source docs (+ co-located expect tier).
function readRows(srcPacks) {
  const rows = [];
  for (const pack of readdirSync(srcPacks, { withFileTypes: true }).filter(d => d.isDirectory())) {
    if ((COLLECTIONS[pack.name] ?? "items") !== "items") continue;
    const dir = join(srcPacks, pack.name);
    for (const f of readdirSync(dir).filter(f => f.endsWith(".json") && !f.endsWith(".expect.json") && !f.startsWith("_"))) {
      const doc = JSON.parse(readFileSync(join(dir, f), "utf8"));
      const expectFile = join(dir, `${f.replace(/\.json$/, "")}.expect.json`);
      const tier = existsSync(expectFile) ? JSON.parse(readFileSync(expectFile, "utf8")).tier : undefined;
      rows.push({
        identifier: doc.system?.identifier ?? doc.name,
        name: doc.name,
        img: doc.img ?? "",
        description: doc.system?.description?.value ?? "",
        tier,
      });
    }
  }
  return rows;
}

// Write CATALOG.md into each module's item packs (only modules that have any).
export function writeCatalogs() {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
  for (const mod of MODULES) {
    const srcPacks = join(repoRoot, mod.dir, "src", "packs");
    if (!existsSync(srcPacks)) continue;
    const rows = readRows(srcPacks);
    if (!rows.length) continue;
    // Catalog lives in the abilities pack dir (where authors look).
    const target = join(srcPacks, "forge-abilities", "CATALOG.md");
    if (!existsSync(join(srcPacks, "forge-abilities"))) continue;
    writeFileSync(target, buildCatalog(rows) + "\n");
    console.log(`[${mod.name}] CATALOG.md written (${rows.length} abilities)`);
  }
}

// `node catalog.mjs` -> regenerate.
if (import.meta.url === `file://${process.argv[1]}`) writeCatalogs();
